server:
  port: 8888
spring:
  datasource:
    url: jdbc\:mysql\://10.110.1.113\:3306/dv_db_assistant?useUnicode\=true&characterEncoding\=utf-8&zeroDateTimeBehavior\=convertToNull
    username: root
    password: qaz2wsx
    driver-class-name: com.mysql.cj.jdbc.Driver
